# Generated by Django 6.0 on 2025-12-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('EN_ESPERA', 'En espera'), ('LLAMADO', 'Llamado'), ('ATENDIDO', 'Atendido')], default='EN_ESPERA', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
